name: Emotes
main: TheNote\Emotes\Emotes
api:
  - 3.0.0
  - 4.0.0
version: 1.0.0
author: §f[§4The§fNote]
description: §1Emote §6Pluin von §f[§4The§fNote]

commands:
  sad:
    description: §6Sad Emote
    usgae: /sad
  angry:
    description: §6Angry Emote
    usage: /angry
  happy:
    description: §6Happy Emote
    usage: /happy
  geil:
    describtion: §6Geil Emote
    usage: /geil
  kevin:
    description: §6Kevin Emote
    usage: /kevin
  stink:
    description: §6Stink Emote
    usage: /stink
  burb:
    description: §6Burb Emote
    usage: /burb
  fart:
    description: §6Fart Emote
    usage: /fart
  toilet:
    description: §6Toilet Emote
    usage: /toilet
  sleepy:
    description: §6Sleepy Emote
    usage: /sleepy 
  emotes:
    description: §6List all Emotes
    usage: /emotes
